app = 'esg-laundry-checker'
primary_region = 'sin'

[build]

[env]
  POWER_THRESHOLD_W = "10"
  STOP_THRESHOLD_W = "5"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
